name: Deploy to GitHub Pages
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  deploy:
    uses: "getpelican/pelican/.github/workflows/github_pages.yml@main"
    permissions:
      contents: "read"
      pages: "write"
      id-token: "write"
    with:
      settings: "publishconf.py"



# name: Deploy to GitHub Pages
# on:
#   push:
#     branches: ["main"]
#   workflow_dispatch:
# jobs:
#   build:
#     name: Build and deploy
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4
#       - name: Set up Python
#         uses: actions/setup-python@v5
#         with:
#           python-version: 3.12
#       - name: Install dependencies
#         run: |
#           pip install pipenv
#           pipenv install
#       - name: Check content directory
#         run: ls -R content
#       - name: Build site
#         run: pipenv run pelican content -s publishconf.py -o output
#       - name: Check output directory
#         run: ls -R output
#       - name: Fix permissions
#         run: |
#           chmod -c -R +rX output | while read line; do
#             echo "::warning title=Invalid file permissions automatically fixed::$line"
#           done
#       - name: Deploy to GitHub Pages
#         uses: peaceiris/actions-gh-pages@v3
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           publish_dir: ./output
